### ISSUE TITLE
GameMain/MetadataAssemblys路径中存放用于作为补充元数据的dll,从哪里找啊？

### ISSUE THREAD

**Issue by maki0315** [Dango1992/UnityGameFramework_Huatuo#1]
![image](https://user-images.githubusercontent.com/62171024/174935072-a3e7a629-bc60-4c1a-b5df-331a347a081d.png)
为什么我这里 不存在这个路径啊
![image](https://user-images.githubusercontent.com/62171024/174935188-2f74adc0-953f-4c09-a5f6-3b8a6f4525eb.png)

**Comment by DangoRyn** [comment]
这个需要打包一次就会存在了

**Comment by maki0315** [comment]
> 这个需要打包一次就存在了

好的，谢谢

**Comment by maki0315** [comment]
> 这个需要打包一次就存在了

我拿到这些dll直接把后缀改成.bytes,然后拷贝到对应的目录下就行了吗

**Comment by DangoRyn** [comment]
是的

**Comment by maki0315** [comment]
> 是的

我已经能跑通了，太感谢了
